# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logowanie.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
import hashlib
from db_conn import dbConnection
from mess import messagebox

class Ui_Form(object):
    
    stanPass = True
    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(563, 175)
        Form.setMinimumSize(QtCore.QSize(563, 175))
        Form.setMaximumSize(QtCore.QSize(563, 175))
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 1, 561, 171))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_image = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_image.setMinimumSize(QtCore.QSize(150, 150))
        #self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.horizontalLayout_2.addWidget(self.label_image)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_password = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_password.setObjectName("label_password")
        self.verticalLayout_2.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.verticalLayout_2.addWidget(self.lineEdit_password)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_email = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_email.setObjectName("label_email")
        self.verticalLayout.addWidget(self.label_email)
        self.lineEdit_email = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.verticalLayout.addWidget(self.lineEdit_email)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        
        self.pushButton_odkryj = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_odkryj.setObjectName("pushButton_odkryj")
        self.verticalLayout_3.addWidget(self.pushButton_odkryj)
        
        
        self.pushButton_zaloguj = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_zaloguj.setObjectName("pushButton_zaloguj")
        self.verticalLayout_3.addWidget(self.pushButton_zaloguj)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton_zaloguj.clicked.connect(self.logowanie)
        self.pushButton_odkryj.clicked.connect(self.odkrywanie)
        
    def odkrywanie(self):
        if self.stanPass == True:
            self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Normal)
            self.stanPass = False
        else:
            self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
            self.stanPass = True
        
       
    
    
    def logowanie(self):
        email = self.lineEdit_email.text()
        password = hashlib.md5(self.lineEdit_password.text().encode('utf-8')).hexdigest()
        db = dbConnection()
        db.connect()
        query = f'SELECT count(*) FROM users WHERE email= %s AND pass= %s'
        params = (email, password)
        row = db.fetchone(query, params)
        db.close()
        if row[0]==1:
            loggedas = f"You are logged as {email}"
            messagebox("Login", loggedas, "Information", "Ok")
        else:
            messagebox("Login problem", "Your email or password is not correct.", "Critical", "Cancel")            
        

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Logowanie"))
        self.label_password.setText(_translate("Form", "Password"))
        self.label_email.setText(_translate("Form", "E-mail"))
        self.pushButton_zaloguj.setText(_translate("Form", "Zaloguj"))
        self.pushButton_odkryj.setText(_translate("Form", "Odkryj hasło"))
        #self.label_image.setText(_translate("Login", ""))
        pixmap = QPixmap('login_graphic.png')
        self.label_image.setPixmap(pixmap)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
